apiVersion: v1
kind: Secret
metadata:
  name: {{ include "toolhive-mcp.secretAzureName" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "toolhive-mcp.labels" . | nindent 4 }}
type: Opaque
stringData:
  client-secret: {{ .Values.oauth.azure.clientSecret | quote }}
